### PR TITLE
🥯 Favorite contacts bug fix

### LINKED ISSUE #343: Favorite Contacts Bug
#### Description
The favorites card is stuck in a forever loading action if there are no mentors that have been favorited. We want to not have the signal that favorited mentors are still loading

#### Screenshots
image

#### Files
`MenteeAppointments.js`
`BookmarkSidebar.js`

#### To Reproduce
- You must have a Mentee profile account
- Have no mentors favorited and go to your Mentee profile

### PR DESCRIPTION
**Pull request by lucianatl**
## Description :star2:

- when there are no favorited contacts, displays "no favorited contacts" instead of spinning icon 
image
Fixes #343

### CODE REVIEW

File: frontend/src/components/BookmarkSidebar.js [hunk 1]
```diff
@@ -28,10 +28,14 @@ function BookmarkSidebar({ bookmarks, unfavorite }) {
         <HeartFilled /> Favorite Contacts
       </div>
       <div className="mentee-bookmark-display">
-        <Spin
-          spinning={!bookmarks || !bookmarks.length}
-          className="bookmark-spin"
-        >
+        <Spin spinning={!bookmarks} className="bookmark-spin">
```
Comment (Leundai) [inline frontend/src/components/BookmarkSidebar.js:31]: Before we used to have a spinning indicator when bookmarked mentors are loading. However now it only shows "No favorite contacts" instead of the loading signal.

I think for this it might be best to add another prop param in the bookmark component that is visible while the useEffect is calling the API from `MenteeAppointments.js`.

File: frontend/src/components/BookmarkSidebar.js [hunk 2]
```diff
@@ -28,10 +28,14 @@ function BookmarkSidebar({ bookmarks, unfavorite }) {
...
+          <div
+            style={
+              !bookmarks.length ? { display: "block" } : { display: "none" }
+            }
+          >
```
Comment (Leundai) [inline frontend/src/components/BookmarkSidebar.js:36]: Just for now, I think we should have the text centered instead of anchored to the side. Also, we can say "No favorited Mentors"

File: frontend/src/components/BookmarkSidebar.js [hunk 3]
```diff
@@ -28,10 +28,14 @@ function BookmarkSidebar({ bookmarks, unfavorite }) {
         <HeartFilled /> Favorite Contacts
       </div>
       <div className="mentee-bookmark-display">
-        <Spin
-          spinning={!bookmarks || !bookmarks.length}
-          className="bookmark-spin"
-        >
+        <Spin spinning={!bookmarks} className="bookmark-spin">
+          <div
```
Comment (Leundai) [inline frontend/src/components/BookmarkSidebar.js:32]: Also, we can have some conditional rendering here instead of css display usage. But lmk if that doesn't work.

**Review by Leundai — CHANGES_REQUESTED** [review]

**Comment by nroy20** [comment]
looks good!

**Review by nroy20 — APPROVED** [review]
looks good!

**Review by Leundai — APPROVED** [review]
gravy
