### PR TITLE
Fix mentee book appointment

### LINKED ISSUE #131: Mentee Book Appointment - connect to backend
### Backend Connection
- remove hardcoding of the words date, time, name etc (see #150) MICHAEL ALREADY DOING THIS
- change tile color to yellow for dates where mentors have available appointments (see #150) MICHAEL ALREADY DOING THIS
- connect to backend and send appointment request when mentee books an appointment DO THIS
- remove appointment time from mentor's availability once booked
### Frontend Form Fixes
- **remove ethnicity** from the appointment request form DO THIS
- Change gender to Male, Female, Non-Binary, and Other DO THIS

NOTE: backend needs to remove some fields and add booleans for allowText and allowCalls issue #140

### PR DESCRIPTION
**Pull request by AzureQDragon**
## Status:
:rocket: Ready

## Description :star2:
Changing mentee booking modal

Fixes #131 

Screenshots:
Modal Screenshots:
image
image
Form Validation when not all required areas are not filled in:
image
Database:
image

 
## TODOs :star:
- [x] Remove Fields
- [x] Connect Backedn
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Review by AngelaLuo49021 — CHANGES_REQUESTED** [review]
Bug: all available appointment times show up as 00:00 - 00:00

**Comment by AzureQDragon** [comment]
> Bug: all available appointment times show up as 00:00 - 00:00

I think that's not a bug but rather a product of the fact that jim watson happens to have all of his appointments at 00:00 - 00:00 since it's currently shown in 24hr time.

**Review by AngelaLuo49021 — COMMENTED** [review]
It still does 00:00 for my times. 
image
image
image

File: frontend/src/components/MenteeAppointmentModal.js [hunk 1]
```diff
@@ -31,7 +30,18 @@ const sampleTimes = [
...
+    email: "Not a valid email",
+  },
+};
+
+function MenteeAppointmentModal(props) {
+  const [form] = Form.useForm();
+  const [timeSlots, setTimeSlots] = useState([]);
+  const [dayTimeSlots, setDayTimeSlots] = useState([]);
   const [appModalVisible1, setAppModalVisible1] = useState(false);
   const [appModalVisible2, setAppModalVisible2] = useState(false);
```
Comment (chyku) [inline frontend/src/components/MenteeAppointmentModal.js:46]: this is kind of weird naming for a state, what does this mean & why are there 2 of them?

**Review by chyku — CHANGES_REQUESTED** [review]
not a full review, just noticed a few things & pls add documentation for unclear code!

File: frontend/src/components/MenteeAppointmentModal.js (hunk 1 above)
Comment (AngelaLuo49021) [reply frontend/src/components/MenteeAppointmentModal.js:46]: @Lam7150

**Review by AngelaLuo49021 — CHANGES_REQUESTED** [review]
Some of the CSS on the form got messed up 
Before:
image
After:
image

Make the bubbles bigger to fit in the time (time is preferably centered too):
image

(highly appreciated but not high pri)
Also could the times not be in military times? include am/pm

File: frontend/src/components/MenteeAppointmentModal.js (hunk 1 above)
Comment (Lam7150) [reply frontend/src/components/MenteeAppointmentModal.js:48]: just saw this oops github didn't send me a notification, but that's the state to open/close the modal's in sequential order (although the naming is weird), I would recommend changing it if you find a better solution though as that was done a bit hastily to meet deadlines

**Review by AngelaLuo49021 — APPROVED** [review]
Beautiful

File: frontend/src/components/MenteeAppointmentModal.js (hunk 1 above)
Comment (chyku) [reply frontend/src/components/MenteeAppointmentModal.js:48]: yea would prefer this changed to mentioning which modal & not a general appmodal

File: frontend/src/components/MenteeAppointmentModal.js [hunk 2]
```diff
@@ -31,10 +32,21 @@ const sampleTimes = [
...
-  const [numInputs, setNumInputs] = useState(11);
+  const [numInputs] = useState(11);
```
Comment (chyku) [inline frontend/src/components/MenteeAppointmentModal.js:49]: if numinputs doesn't change you can make this const numinputs = 11

File: frontend/src/components/MenteeAppointmentModal.js [hunk 3]
```diff
@@ -62,32 +117,67 @@ function MenteeAppointmentModal() {
...
   }
 
   function closeModals() {
+    setTime(null);
     setAppModalVisible1(false);
     setAppModalVisible2(false);
   }
 
-  function handleBookAppointment() {
+  // Move on to next page if time is truthy
```
Comment (chyku) [inline frontend/src/components/MenteeAppointmentModal.js:129]: IMO the "if time is truthy" part isn't necessary as the code `if (time)` says it for you, but it would be helpful if you could move this to line 132 and describe that what's happening w all the setAppModalVisibles is that you're moving onto the next page

File: frontend/src/components/MenteeAppointmentModal.js [hunk 4]
```diff
@@ -62,32 +117,67 @@ function MenteeAppointmentModal() {
...
+    }
+
+    // Manually set keys to values for accepted and timeslot
+    appointment["accepted"] = false;
+    appointment["timeslot"] = {
+      start_time: moment(time.start_time.$date).format(),
+      end_time: moment(time.end_time.$date).format(),
+    };
+
+    // POST request to create mentee appointment
```
Comment (chyku) [inline frontend/src/components/MenteeAppointmentModal.js:159]: also not super necessary comment- if your code says what it's doing, no need to comment

File: frontend/src/components/MenteeAppointmentModal.js [hunk 5]
```diff
@@ -161,192 +262,285 @@ function MenteeAppointmentModal() {
...
+          id="appointment-form"
+          form={form}
+          onFinish={handleBookAppointment}
+          validateMessages={validationMessage}
+          scrollToFirstError
+        >
+          <div className="modal-container">
+            <div className="modal-mentee-appointment-heading-container">
+              <div className="modal-mentee-appointment-heading-text">
+                Mentoring Session with Bernie Sanders
```
Comment (chyku) [inline frontend/src/components/MenteeAppointmentModal.js:280]: can you put a todo here or fill in mentor name if it's easy to

File: frontend/src/components/css/Modal.scss [hunk 6]
```diff
@@ -108,4 +108,27 @@
...
+
+.modal-mentee-appointment-contact-container {
+    display: inline;
+}
+
+
+// This is probably bad coding practice so probably want to replace
+.ant-form-item-has-error{
+    background-color: inherit !important;
+    border-color: inherit !important;
```
Comment (chyku) [inline frontend/src/components/css/Modal.scss:122]: yea what is going on here lol

File: frontend/src/utils/consts.js [hunk 7]
```diff
@@ -74,3 +64,20 @@ export const AGES = [
   "45 to 49",
   "Over 60",
 ];
+
+// Keys for fields
+export const KEYS = [
```
Comment (chyku) [inline frontend/src/utils/consts.js:69]: can u make the constant name specific to your form (i.e. appointment form keys)

**Review by chyku — CHANGES_REQUESTED** [review]
mostly nits but smol things, overall looks aight pls try to avoid sus code & mark todos where u think its sus lol

File: frontend/src/components/css/Modal.scss (hunk 6 above)
Comment (AzureQDragon) [reply frontend/src/components/css/Modal.scss:122]: So in order to override ant design changes I had to use !important, but I don't know if there is a better way to do this

**Review by chyku — APPROVED** [review]
we do love to see it!! also if there are no issues listed for the todos in here (replacing bernie sanders, timezone), pls write some up
